In [1]:
import numpy as np

In [2]:
# 二进制和文本
# 二进制又分 numpy 专用的格式化二进制类型和无格式类型

In [9]:
a = np.arange(0, 12)
a.shape = 3,4
print(a)
# tofile 将数组中的数据以二进制格式写入文件
a.tofile('a.bin')
# tofile 输出的数据没有格式，读取回来数据时需要格式化数据
b = np.fromfile('a.bin', dtype=np.int32)
print('b = %s' % b)
# 读入的时候设置正确的dtype和shape才能保证数据一致
# 按照原数据的shape修改读取后数据的shape
b.shape = 3, 4
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b = [ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
