In [42]:
import numpy as np
import math 
import time

In [16]:
a = np.array([[0,1,2], [3,4,5], [6,7,8]], dtype=np.float32)
print(a)
# 取
# 行步长， 列步长
b = a[::2, ::2]
print(b)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]]
[[ 0.  2.]
 [ 6.  8.]]


In [17]:
# linspace函数创建数组, params -> 初值， 终值，元素个数， 是否包含终值(缺省为True)
x = np.linspace(0, 5, 5)
print(x)
# ufunc函数 -> universal function
# 基于c实现，速度快
# 对数组中的每个元素进行正弦计算
y = np.sin(x)
print(y)

[ 0.    1.25  2.5   3.75  5.  ]
[ 0.          0.94898462  0.59847214 -0.57156132 -0.95892427]


In [18]:
# 对比numpy.math和python标准库的math.sin计算速度
x = [i * 0.001 for i in range(1000000)]
start = time.clock()
# enumerate -> 枚举
# 遍历
for i, t in enumerate(x):
    x[i] = math.sin(t)
print('math.sin => %s' % (float(time.clock()) - float(start)))

x = np.array(x)
start = time.clock()
np.sin(x)
print('np.sin => %s' % (float(time.clock()) - float(start)))

math.sin => 0.2443837434292533
np.sin => 0.007756388311591422


In [19]:
a = np.arange(0, 4)
print(a)
b = np.arange(3, 7)
print(b)
# 对应元素的和
c = np.add(a, b)
print(c)

[0 1 2 3]
[3 4 5 6]
[3 5 7 9]


In [22]:
'''
y = x1 + x2:	add(x1, x2 [, y])
y = x1 - x2:	subtract(x1, x2 [, y])
y = x1 * x2:	multiply (x1, x2 [, y])
y = x1 / x2:	divide (x1, x2 [, y]), 如果两个数组的元素为整数，那么用整数除法
y = x1 / x2:	true divide (x1, x2 [, y]), 总是返回精确的商
y = x1 // x2:	floor divide (x1, x2 [, y]), 总是对返回值取整
y = -x:	negative(x [,y])
y = x1**x2:	power(x1, x2 [, y])
y = x1 % x2:	remainder(x1, x2 [, y]), mod(x1, x2, [, y])
'''

'\ny = x1 + x2:\tadd(x1, x2 [, y])\ny = x1 - x2:\tsubtract(x1, x2 [, y])\ny = x1 * x2:\tmultiply (x1, x2 [, y])\ny = x1 / x2:\tdivide (x1, x2 [, y]), 如果两个数组的元素为整数，那么用整数除法\ny = x1 / x2:\ttrue divide (x1, x2 [, y]), 总是返回精确的商\ny = x1 // x2:\tfloor divide (x1, x2 [, y]), 总是对返回值取整\ny = -x:\tnegative(x [,y])\ny = x1**x2:\tpower(x1, x2 [, y])\ny = x1 % x2:\tremainder(x1, x2 [, y]), mod(x1, x2, [, y])\n'

In [23]:
# 广播
# 当我们使用ufunc函数对两个数组进行计算时，ufunc函数会对这两个数组的对应元素进行计算，因此它要求这两个数组有相同的大小(shape相同)。如果两个数组的shape不同的话，会进行如下的广播(broadcasting)处理：
# 让所有输入数组都向其中shape最长的数组看齐，shape中不足的部分都通过在前面加1补齐
# 输出数组的shape是输入数组shape的各个轴上的最大值
# 如果输入数组的某个轴和输出数组的对应轴的长度相同或者其长度为1时，这个数组能够用来计算，否则出错
# 当输入数组的某个轴的长度为1时，沿着此轴运算时都用此轴上的第一组值

In [33]:
a = a.repeat(5, axis=1)
print(a)
b = b.repeat(6, axis=0)
print(b)

[[ 0  0  0 ...,  0  0  0]
 [10 10 10 ..., 10 10 10]
 [20 20 20 ..., 20 20 20]
 [30 30 30 ..., 30 30 30]
 [40 40 40 ..., 40 40 40]
 [50 50 50 ..., 50 50 50]]
[0 0 0 ..., 4 4 4]


In [38]:
# ogrid -> 像一个多维数组一样，用切片组元作为下标进行存取，返回的是一组可以用来广播计算的数组
# 开始值:结束值:步长，和np.arange(开始值, 结束值, 步长)类似
x, y = np.ogrid[0:5, 0:5]
print(x)
print(y)
# 开始值:结束值:长度j，当第三个参数为虚数时，它表示返回的数组的长度，和np.linspace(开始值, 结束值, 长度)类似
a, b = np.ogrid[0:1:4j, 0:1:3j]
print(a)
print(b)

[[0]
 [1]
 [2]
 [3]
 [4]]
[[0 1 2 3 4]]
[[ 0.        ]
 [ 0.33333333]
 [ 0.66666667]
 [ 1.        ]]
[[ 0.   0.5  1. ]]


In [44]:
# 1 + 2 + 3
print(np.add.reduce([1,2,3]))
# 1, 4 + 2, 5 + 3, 6
print(np.add.reduce([[1,2,3], [4,5,6]], axis=1))

6
[ 6 15]
