In [14]:
import numpy as np

In [ ]:
# 二进制和文本
# 二进制又分 numpy 专用的格式化二进制类型和无格式类型

In [ ]:
a = np.arange(0, 12)
a.shape = 3,4
print(a)
# tofile 将数组中的数据以二进制格式写入文件
a.tofile('a.bin')
# tofile 输出的数据没有格式，读取回来数据时需要格式化数据
b = np.fromfile('a.bin', dtype=np.int32)
print('b = %s' % b)
# 读入的时候设置正确的dtype和shape才能保证数据一致
# 按照原数据的shape修改读取后数据的shape
b.shape = 3, 4
print(b)
print('-----------------------')
# 使用load和save Numpy专用的二进制类型保存数据，会自动处理元素类型和shape的信息
np.save('a.npy', a)
c = np.load('a.npy')
print(c)

In [16]:
'''
将多个数组保存到一个文件中的话，可以使用numpy.savez函数。
savez函数的第一个参数是文件名，其后的参数都是需要保存的数组，也可以使用关键字参数为数组起一个名字，非关键字参数传递的数组会自动起名为arr_0, arr_1, ...。
savez函数输出的是一个压缩文件(扩展名为npz)，其中每个文件都是一个save函数保存的npy文件，文件名对应于数组名。
load函数自动识别npz文件，并且返回一个类似于字典的对象，可以通过数组名作为关键字获取数组的内容
'''
a = np.array([[1,2,3], [4,5,6]])
b = np.arange(0, 1.0, 0.1)
# 正弦
c = np.sin(b)
# 可以指定键 值， 也可以使用默认的 键
np.savez('result.npz', a, b_ = b, sin_array = c)
# 读取
r = np.load('result.npz')
print(r)
# a
print(r['arr_0'])
# b
print(r['b_'])
# c
print(r['sin_array'])

[[1 2 3]
 [4 5 6]]
[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9]
[ 0.          0.09983342  0.19866933  0.29552021  0.38941834  0.47942554
  0.56464247  0.64421769  0.71735609  0.78332691]


In [21]:
# 使用 savetxt 和 loadtxt 可以读写 1维 和 2维 的数组
# 广播 -> 4 行，-1(剩下的自动匹配)
a = np.arange(0, 12, 0.5).reshape(4, -1)
# 缺省(默认) 按'%.18e'格式保存数据，以空格分隔
np.savetxt('a.txt', a)
print(np.loadtxt('a.txt'))
# 修改为保存整数，以逗号分隔
np.savetxt('a.txt', a, fmt='%d', delimiter=',')
# 获取时需要使用 ，分隔
print(np.loadtxt('a.txt', delimiter=','))

[[  0.    0.5   1.    1.5   2.    2.5]
 [  3.    3.5   4.    4.5   5.    5.5]
 [  6.    6.5   7.    7.5   8.    8.5]
 [  9.    9.5  10.   10.5  11.   11.5]]
[[  0.   0.   1.   1.   2.   2.]
 [  3.   3.   4.   4.   5.   5.]
 [  6.   6.   7.   7.   8.   8.]
 [  9.   9.  10.  10.  11.  11.]]


In [30]:
# 将多个数组存储到一个npy文件中
a = np.arange(8)
print(a)
b = np.add.accumulate(a)
print(b)
c = a + b
f = file('result.npy', 'wb')
# 顺序保存a, b, c保存至文件对象 f
np.save(f, a)
np.save(f, b)
np.save(f, c)
f.close()
# 顺序读出
print(np.load(f))
print(np.load(f))

[0 1 2 3 4 5 6 7]
[ 0  1  3  6 10 15 21 28]


AttributeError: module 'numpy' has no attribute 'read'