In [1]:
import numpy as np

In [28]:
'''
矩阵运算
'''
# 划重点 -> 不推荐在较复杂的程序中使用 matrix
a = np.matrix([[1,2,3], [5,5,6], [7,9,9]])
# a ** -1  -> a 的 逆矩阵
print(a * a ** -1)
# reshape -> 转为二维 -> 3行5列
b = np.arange(15).reshape(3,5)
print(b)
# T 转置
# 5行3列
print(b.T)

[[  1.00000000e+00   0.00000000e+00  -5.55111512e-17]
 [  4.44089210e-16   1.00000000e+00   3.33066907e-16]
 [  4.44089210e-16   0.00000000e+00   1.00000000e+00]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [39]:
# 矩阵的乘积可以使用dot函数进行计算。
# 对于二维数组，它计算的是矩阵乘积，对于一维数组，它计算的是其点积。
# 将一维数组当作列矢量或者行矢量进行矩阵运算时， 使用reshape函数将一维数组转换为二维数组
'''
dot : 对于两个一维的数组，计算的是这两个数组对应下标元素的乘积和(数学上称之为内积)；
      对于二维数组，计算的是两个数组的矩阵乘积；
      对于多维数组，它的通用计算公式如下，即结果数组中的每个元素都是：数组a的最后一维上的所有元素与数组b的倒数第二位上的所有元素的乘积和
      dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
'''
a = np.arange(12).reshape(2,3,2)
print(a)
print('---------------')
b = np.arange(12, 24).reshape(2,2,3)
print(b)
print('---------------')
c = np.dot(a, b)
print(c)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
---------------
[[[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]
---------------
[[[[ 15  16  17]
   [ 21  22  23]]

  [[ 69  74  79]
   [ 99 104 109]]

  [[123 132 141]
   [177 186 195]]]


 [[[177 190 203]
   [255 268 281]]

  [[231 248 265]
   [333 350 367]]

  [[285 306 327]
   [411 432 453]]]]


In [40]:
# inner : 和dot乘积一样，对于两个一维数组，计算的是这两个数组对应下标元素的乘积和；
# 对于多维数组，它计算的结果数组中的每个元素都是：
# 数组a和b的最后一维的内积，因此数组a和b的最后一维的长度必须相同
# inner(a, b)[i,j,k,m] = sum(a[i,j,:]*b[k,m,:])

In [41]:
# outer : 只按照一维数组进行计算，如果传入参数是多维数组，则先将此数组展平为一维数组之后再进行运算。
# outer乘积计算的列向量和行向量的矩阵乘积
print(np.outer([1,2,3], [4,5,6,7]))

[[ 4  5  6  7]
 [ 8 10 12 14]
 [12 15 18 21]]


In [42]:
'''
矩阵中更高级的一些运算可以在NumPy的线性代数子库linalg中
inv函数计算逆矩阵，solve函数可以求解多元一次方程组
solve函数有两个参数a和b。a是一个N*N的二维数组，而b是一个长度为N的一维数组，solve函数找到一个长度为N的一维数组x，使得a和x的矩阵乘积正好等于b，数组x就是多元一次方程组的解
'''
# 10行10列
a = np.random.rand(10, 10)
print(a)

[[ 0.50944311  0.90403158  0.23693459  0.26589754  0.37246503  0.40667989
   0.97662308  0.59530152  0.96700061  0.92775314]
 [ 0.22941022  0.60385948  0.03332949  0.32331262  0.66701838  0.20332524
   0.79044818  0.29518517  0.90634345  0.6249004 ]
 [ 0.21630778  0.56271688  0.07066986  0.94466844  0.49545764  0.29521657
   0.24586989  0.76715098  0.58385558  0.91705768]
 [ 0.6093676   0.1850144   0.08330986  0.72404438  0.51061787  0.48182324
   0.25720342  0.13190087  0.09789196  0.74161163]
 [ 0.08828856  0.93492168  0.05223361  0.27914167  0.65494041  0.29026927
   0.04843299  0.60598055  0.33095893  0.58497799]
 [ 0.25657812  0.48366503  0.27044988  0.04661375  0.39109992  0.19230855
   0.46420552  0.24912978  0.57812472  0.44208596]
 [ 0.37516549  0.74783134  0.95983675  0.10325312  0.3523981   0.63426768
   0.99103856  0.63168376  0.73540174  0.39329464]
 [ 0.43176688  0.66629486  0.46197438  0.02052098  0.64826996  0.82725685
   0.73338887  0.49052192  0.20711735  0.85525205]
