In [1]:
import numpy as np

In [9]:
a = np.arange(0, 60, 10).reshape((-1, 1)) + np.arange(5)
print(a)
# 二维数组切片
# 第 0 行 第 2 位下标
print(a[[0, 1, 2], [2, 3, 4]])
# 第 4 行 的 2，3, 4下标
print(a[4, [2, 3, 4]])
# 从第 4 行开始后面的都要
print(a[4:, [2, 3, 4]])

# 布尔值索引
i = np.array([True, True, False, True, False, False])
print(a[i])
# 取所有行的第 3 个下标
print(a[i, 3])

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]
 [50 51 52 53 54]]
[ 2 13 24]
[42 43 44]
[[42 43 44]
 [52 53 54]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [30 31 32 33 34]]
[ 3 13 33]


In [27]:
# 元素去重
a = np.array((1, 1, 2, 1, 1, 3, 4, 5, 6, 4, 3, 2))
print(np.unique(a).reshape(3,-1))
# 二维数组去重
b = np.array(((1, 2), (2, 3), (1, 2), (3,4)))
print(b)
# 先取出放入元组中，然后就可以在放入set集合中，然后利用集合的特性去重
print('去重: %s \n' % np.array(list(set([tuple(t) for t in b]))))

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [2 3]
 [1 2]
 [3 4]]
去重: [[1 2]
 [3 4]
 [2 3]] 



In [30]:
# 矩阵相乘
a = np.arange(1, 10) .reshape(3, 3)
print(a)
b = a + 10
print(b)
print('-----------------------')
# a 的第一行 乘以 b 的第一列 再求和
print(np.dot(a, b))
# 对应位置相乘
print('------------------------')
print(a * b)
print(np.multiply(a, b))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
-----------------------
[[ 90  96 102]
 [216 231 246]
 [342 366 390]]
------------------------
[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]
[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]


In [32]:
# 拼接
a = np.arange(1, 10)
b = np.arange(20, 30)
print(np.concatenate((a, b)))

[ 1  2  3  4  5  6  7  8  9 20 21 22 23 24 25 26 27 28 29]
