In [2]:
import numpy as np

In [17]:
# range() 创建int类类 => list
# arange() 可以使用float类型 => array
# 0 - 60 (含头不含尾) 步长为 10  reshape -> 给予数组一个新的形状，而不改变它的数据
a = np.arange(0, 60, 10).reshape((-1, 1)) + np.arange(6)
print(a)
# 下面俩和上面对比着看就明白了
print(np.arange(6))
print(np.arange(0, 60, 10))

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]
[0 1 2 3 4 5]
[ 0 10 20 30 40 50]


In [34]:
# 需要3个指针和3个整数对象，对于数值运算比较浪费内存和cpu
L = [1, 2, 3]
# 所以使用Numpy提供的ndarray对象 -> 存储单一数据类型的多维数组
_L = np.array(L)
print(_L)
# 获取长度
print(_L.shape)
b = np.array([[1,2], [2,3], [4,5], [6,7], [8,9], [10, 11]])
print(b)
print(b.shape)
# 可以强制性修改shape, 当某个轴为-1时，将根据数组元素的个数自动计算此轴的长度
b.shape = 2, -1
print(b)
print(b.shape)
# 使用reshape方法，可以创建改变了尺寸的新数组，原数组的shape保持不变, 并且reshape之后的数组与原数组更享内存数据(指向一致)
c = b.reshape((3, -1))
print(c)
# 数据类型
print(c.dtype)
# 指定数据类型
d = np.array([[2,3], [4,5]], dtype=np.float)
print(d)
# astype -> 数据类型转换
nf = d.astype(np.int)
print(nf)

[1 2 3]
(3,)
[[ 1  2]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
(6, 2)
[[ 1  2  2  3  4  5]
 [ 6  7  8  9 10 11]]
(2, 6)
[[ 1  2  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
int32
[[ 2.  3.]
 [ 4.  5.]]
[[2 3]
 [4 5]]


In [4]:
# 线性
# linspace函数创建数组, params -> 初值， 终值，元素个数， 是否包含终值(缺省为True)
a = np.linspace(1, 10, 10)
print(a)
# 不包含终值
b = np.linspace(1, 10, 10, endpoint=False)
print(b)

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
[ 1.   1.9  2.8  3.7  4.6  5.5  6.4  7.3  8.2  9.1]


In [50]:
# 对数
# 创建等比数列
# 10 ** 2 10的2次方
# 现实计算中 10^2 为10的2次方，但实际在算法中不是，上面的才是
# 当前起始值为 10**1， 终止值为 10**2, 有9个数的等比数列, 默认包含终止值
d = np.logspace(1, 2, 9)
# 10**1 - 10**4 
_d = np.logspace(1, 4, 4)
print(d)
print(_d)
print(10**3)
print(10^3)
# 创建基础值， 默认为10
# 2 ** 0  - 2 ** 10
g = np.logspace(0, 10, 11, base=2)
print(g)
print(2**0)
print(2**10)

[  10.           13.33521432   17.7827941    23.71373706   31.6227766
   42.16965034   56.23413252   74.98942093  100.        ]
[    10.    100.   1000.  10000.]
1000
9
[  1.00000000e+00   2.00000000e+00   4.00000000e+00   8.00000000e+00
   1.60000000e+01   3.20000000e+01   6.40000000e+01   1.28000000e+02
   2.56000000e+02   5.12000000e+02   1.02400000e+03]
1
1024


In [51]:
# 使用frombuffer, fromstring, fromfile等函数可以从字节序列创建数组
st = 'abcd'
# 对应ASCALL码值
g = np.fromstring(st, dtype=np.int8)
print(g)

[ 97  98  99 100]


In [69]:
# 存取
# 含头不含尾
a = np.arange(10)
print(a)
print(a[3])
# 切片[3:5] -> 含头不含尾，下标从第3位开始截取到第5位
print(a[3:5])
# 省略开始，则从0开始, 或者省略最后
print(a[:3])
print(a[3:])
# 步长为2(相隔2位)
print(a[2:8:2])
# 头尾省略，步长为-1 -> 翻转数组
print(a[::-1])
# 切片的数据和原始数据指向一致，共享数据
a[1:4] = 10, 20, 30
print(a)

b = a[1:4]
b[0] = 200
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
3
[3 4]
[0 1 2]
[3 4 5 6 7 8 9]
[2 4 6]
[9 8 7 6 5 4 3 2 1 0]
[ 0 10 20 30  4  5  6  7  8  9]
[  0 200  20  30   4   5   6   7   8   9]
[200  20  30]


In [72]:
# 根据整数数组存取
# 当使用整数序列对数组元素进行存取时，将整个整数序列中的每个元素作为下标，整数序列可以是列表或者是数组
# 使用整数序列作为下标获得的数组不和原始数组共享空间
a = np.logspace(0, 9, 10, base=2)
print(a)
i = np.arange(0, 10, 2)
print(i)
# 利用i做下标取a的数据
b = a[i]
print(b)
b[3] = 333
print(b)
print(a)

[   1.    2.    4.    8.   16.   32.   64.  128.  256.  512.]
[0 2 4 6 8]
[   1.    4.   16.   64.  256.]
[   1.    4.   16.  333.  256.]
[   1.    2.    4.    8.   16.   32.   64.  128.  256.  512.]


In [5]:
# 随机生成 10 个 0 - 1 中均匀分布的随机数 
a = np.random.rand(10)
print(a)
print(a > 0.5)
# 取出大于0.5的项
b = a[a > 0.5]
print('b = %s' % b)
# 将原始数据中 大于 0.5 的数据都强制指定为 0.5
a[a > 0.5] = 0.5
# b 不会受影响
print(a)
print(b)

[ 0.43910249  0.48019996  0.88595946  0.55719824  0.78560203  0.65411196
  0.37708933  0.84864324  0.08989414  0.33993053]
[False False  True  True  True  True False  True False False]
b = [ 0.88595946  0.55719824  0.78560203  0.65411196  0.84864324]
[ 0.43910249  0.48019996  0.5         0.5         0.5         0.5
  0.37708933  0.5         0.08989414  0.33993053]
[ 0.88595946  0.55719824  0.78560203  0.65411196  0.84864324]


In [82]:
# 行向量
a = np.arange(0, 60, 10)
print(a)
# 转为列向量
b = a.reshape((-1,1))
print(b)
# 行加列
f = a + b
print(f)

[ 0 10 20 30 40 50]
[[ 0]
 [10]
 [20]
 [30]
 [40]
 [50]]
[[  0  10  20  30  40  50]
 [ 10  20  30  40  50  60]
 [ 20  30  40  50  60  70]
 [ 30  40  50  60  70  80]
 [ 40  50  60  70  80  90]
 [ 50  60  70  80  90 100]]


In [5]:
# 合并上面的代码
a = np.arange(0, 60, 10).reshape((-1, 1))+np.arange(6)
print(a)
# 二维数组切片 行 列
# 第 0 行的第 2 个下标
print(a[[0,1,2], [2,3,4]])
# 行步长， 列步长
print(a[::2, ::2])

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]
[ 2 13 24]
[[ 0  2  4]
 [20 22 24]
 [40 42 44]]


In [12]:
# 定义结构数组
personType = np.dtype({
    'names': ['name', 'age', 'weight'],
    # formats -> 格式
    # str32  
    # int32
    # float32
    'formats': ['S32', 'i', 'f']
})
a = np.array([('LaoPo', 27, 60.9), ('Me', 24, 64.1)], dtype=personType)
# b -> byte 字节字符
print(a)
print(a[1])
# 获取后数据共享
m = a[1]
print(m)
m['name'] = 'My'
print(a)
print(m)

[(b'LaoPo', 27,  60.90000153) (b'Me', 24,  64.09999847)]
(b'Me', 24,  64.09999847)
(b'Me', 24,  64.09999847)
[(b'LaoPo', 27,  60.90000153) (b'My', 24,  64.09999847)]
(b'My', 24,  64.09999847)
None


In [ ]:
# 内存对齐
# C语言的结构体为了内存寻址方便，会自动的添加一些填充用的字节，这叫做内存对齐。
# 例如如果把下面的name[32]改为name[30]的话，由于内存对齐问题，在name和age中间会填补两个字节，最终的结构体大小不会改变。
# 因此如果numpy中的所配置的内存大小不符合C语言的对齐规范的话，将会出现数据错位。
# 为了解决这个问题，在创建dtype对象时，可以传递参数align=True，这样numpy的结构数组的内存对齐和C语言的结构体就一致了